workspace 'TestSDK.xcworkspace'
project 'TestSDK/TestSDK.xcodeproj'
project 'TestDemo/TestDemo.xcodeproj'
project 'OCTestDemo/OCTestDemo.xcodeproj'


abstract_target 'CommonPods' do  
    
  #公用pods
  use_frameworks!

  # swift
  pod 'SnapKit', '4.0.1'

  # oc
  pod 'MBProgressHUD','1.1.0'
  
  # 极光推送 (.a 静态库)
  pod 'JPush'
  
  # ATAuthSDK.framework 阿里云认证SDK手动添加

  
  ####### project分别处理 #######
  target 'TestSDK' do
      platform :ios, '9.0'
      project 'TestSDK/TestSDK.xcodeproj'
  end
  
  target 'TestDemo' do
      platform :ios, '9.0'
      project 'TestDemo/TestDemo.xcodeproj'
  end
  
  target 'OCTestDemo' do
      platform :ios, '9.0'
      project 'OCTestDemo/OCTestDemo.xcodeproj'
  end
  ####### project分别处理 #######

end
